language: python
python:
  - 2.7
  - 3.4
env:
  - EXE_TRAVIS=1
cache: apt
before_install:
  - sudo apt-get install iverilog
  - sudo apt-get install graphviz
  - pip install pygraphviz jinja2
before_script:
  - pip freeze
script:
#  - export EXE_TRAVIS=1
  - make